version: "3.7"

services:
    elixir:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        volumes: 
            - .:/usr/src/app
        env_file:
            - docker.environment
        networks: 
            - default